shipped_devise_project/config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :boat_jobs
  resources :jobs
  resources :boats

  get 'users/index'

  get '/profile' => 'users#show', as: 'user'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords' 
  }
  root to: "home#index" #localhost:3000 
end

shipped_devise_project/app/models/boat.rb
class Boat < ApplicationRecord
  has_many :jobs, through: :boat_jobs
  has_many :boat_jobs
  belongs_to :user

  validates :name_of_boat, presence: true, uniqueness: true 

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/



end

shipped_devise_project/app/controllers/boats_controller.rb
class BoatsController < ApplicationController
  def index
    @boats = Boat.all
  end

  def new
    @boat = Boat.new
  end

  def create
    @boat = current_user.boats.new(boat_params)
    if @boat.save
      redirect_to user_path
 
    end
  end

  def show
  end

  def edit
    set_boat
  end

  def update
    set_boat
    if @boat.update(boat_params)
      redirect_to user_path
    end
  end

  def destroy
    set_boat
    if @boat.destroy
      redirect_to user_path
    end
  end

  private

  def set_boat
    @boat = Boat.find(params[:id])
  end

  def boat_params
    params.require(:boat).permit(:name_of_boat, :container_capacity, :location, :user_id)
  end

end

shipped_devise_project/app/helpers/boats_helper.rb
module BoatsHelper
end

shipped_devise_project/app/views/boats/_boat.html.erb
Boat Name: <%= boat.name_of_boat %><br>
Container Capacity: <%= boat.container_capacity %><br>
Boat Location: <%= boat.location %><br>
<%= image_tag boat.avatar.url %>
<%= link_to 'Edit', edit_boat_path(boat) %> |
<%= link_to 'Delete', boat, method: :delete %>
<hr>

shipped_devise_project/app/views/boats/_form.html.erb
<%= form_for @boat , :url => boats_path, :html => { :multipart => true } do |f| %>
	
	<div class="field">
		<%= f.label :name_of_boat %>
		<%= f.text_field :name_of_boat %><br>
	</div>

	<div class="field">
		<%= f.label :container_capacity %>
		<%= f.text_field :container_capacity %><br>
	</div>

	<div class="field">	
		<%= f.label :location %>
		<%= f.text_field :location%><br>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>

	<div class="field">
		<%= f.file_field :avatar %>
	</div>
<% end %>

shipped_devise_project/app/views/boats/create.html.erb
<h1>Boats#create</h1>
<p>Find me in app/views/boats/create.html.erb</p>

shipped_devise_project/app/views/boats/destroy.html.erb
<h1>Boats#destroy</h1>
<p>Find me in app/views/boats/destroy.html.erb</p>

shipped_devise_project/app/views/boats/edit.html.erb
<h1>Boats#edit</h1>
<p>Find me in app/views/boats/edit.html.erb</p>

<%= render 'form' %>

shipped_devise_project/app/views/boats/index.html.erb
<h1>Boats#index</h1>
<p>Find me in app/views/boats/index.html.erb</p>
<%= render 'form' %>

shipped_devise_project/app/views/boats/new.html.erb
<h1>Boats#new</h1>
<p>Find me in app/views/boats/new.html.erb</p>

<%= render 'form' %>

  

shipped_devise_project/app/views/boats/show.html.erb
<h1>Boats#show</h1>
<p>Find me in app/views/boats/show.html.erb</p>
<%= render 'form' %>

shipped_devise_project/app/views/boats/update.html.erb
<h1>Boats#update</h1>
<p>Find me in app/views/boats/update.html.erb</p>