shipped_devise_project/config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :boat_jobs
  resources :jobs
  resources :boats

  get 'users/index'

  get '/profile' => 'users#show', as: 'user'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords' 
  }
  root to: "home#index" #localhost:3000 
end

shipped_devise_project/app/models/job.rb
class Job < ApplicationRecord
	has_many :boats, through: :boat_jobs
	has_many :boat_jobs

	validates :job_name, presence: true, uniqueness: true 
	validates :job_description, length: {in: 50..200}
end

shipped_devise_project/app/controllers/jobs_controller.rb
jobclass JobsController < ApplicationController
  def index
    @jobs = Job.all
  end

  def new #This will lead me to jobs#new 
     @job = Job.new
  end

  def create
    @job = Job.new(job_params)
    if @job.save
      redirect_to user_path
    end
  end

  def show
  end

  def edit
    set_job
  end

  def update
    set_job
    if @job.update(job_params)
      redirect_to user_path
    end
  end

  def destroy
    set_job
    if @job.destroy
      redirect_to user_path
    end
  end

  private

  def set_job
    @job = Job.find(params[:id])
  end

  def job_params
    params.require(:job).permit(:job_name, :job_description, :origin, :destination, :containers_needed, :cost)
  end
end

shipped_devise_project/app/helpers/job_helper.rb
module JobHelper
end

shipped_devise_project/app/views/jobs/_form.html.erb
<%= form_for @job do |f| %>

	<%= f.label :job_name %>
	<%= f.text_field :job_name %>
	
	<%= f.label :job_description %>
	<%= f.text_field :job_description %>

	<%= f.label :origin %>
	<%= f.text_field :origin %>

	<%= f.label :destination %>
	<%= f.text_field :destination %>

	<%= f.label :conatiners_needed %>
	<%= f.text_field :containers_needed %>

	<%= f.label :cost %>
	<%= f.text_field :cost %>
	<%= f.submit %>
	
<% end %>

shipped_devise_project/app/views/jobs/_job.html.erb
Job Description: <%= job.job_description %><br>
Origin: <%= job.origin %><br>
Destination: <%= job.destination %><br>
Containers Needed: <%= job.containers_needed %><br>
<%= render 'boat_jobs/form', job: job %>
<%= link_to 'Edit', edit_job_path(job) %> |
<%= link_to 'Delete', job, method: :delete %>
<hr>

shipped_devise_project/app/views/jobs/create.html.erb
<h1>Job#create</h1>
<p>Find me in app/views/job/create.html.erb</p>

shipped_devise_project/app/views/jobs/destroy.html.erb
<h1>Job#destroy</h1>
<p>Find me in app/views/job/destroy.html.erb</p>

shipped_devise_project/app/views/jobs/edit.html.erb
<h1>Job#edit</h1>
<p>Find me in app/views/job/edit.html.erb</p>

<%= render 'form' %>

shipped_devise_project/app/views/jobs/index.html.erb
<h1>Job#index</h1>
<p>Find me in app/views/job/index.html.erb</p>

shipped_devise_project/app/views/jobs/new.html.erb
<h1>Job#new</h1>
<p>Find me in app/views/job/new.html.erb</p>

<%= render 'form' %>

shipped_devise_project/app/views/jobs/show.html.erb
<h1>Job#show</h1>
<p>Find me in app/views/job/show.html.erb</p>

shipped_devise_project/app/views/jobs/update.html.erb
<h1>Job#update</h1>
<p>Find me in app/views/job/update.html.erb</p>