Rails_Blog/config/routes.rb
Rails.application.routes.draw do
#Sessions routes 
  get 'sessions/new'
  post 'sessions/create'
  delete 'sessions/destroy'
#Friendships routes
  post 'friendships/create'
  delete 'friendships/destroy'
#Users, posts, comments routes 
  resources :users  
  resources :posts
  resources :comments
  
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Rails_Blog/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

Rails_Blog/app/models/friendship.rb
class Friendship < ApplicationRecord
	belongs_to :user
	belongs_to :friend, :class_name => "User"
end

Rails_Blog/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
end

Rails_Blog/app/models/user.rb
class User < ApplicationRecord
	has_many :posts, dependent: :destroy 
	has_many :comments, dependent: :destroy
	has_many :friendships
	has_many :friends, :through => :friendships

# def full_name 
# 	@user=User.first
# 	@user.full_name
# end


end

Rails_Blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

	def current_user
		if session[:user_id]
			User.find(session[:user_id])
		end
	end
end

Rails_Blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all
  end

  def new
    @comment = Comment.new
  end

  def create
    @post = @Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end
  def comment_params
        params.require(:comment).permit(:user_id, :post_id, :etc)
   end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

Rails_Blog/app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
	def create
		@friendship = current_user.friendships.build(:friend_id => params[:friend_id])
		  if @friendship.save
		    flash[:notice] = "Added friend."
		    redirect_to root_url
		  else
		    flash[:error] = "Unable to add friend."
		    redirect_to root_url
		end
	end

	def destroy
		@friendship = current_user.friendships.find(params[:id])
		@friendship.destroy
		flash[:notice] = "Removed friendship."
		redirect_to current_user
	end
end

Rails_Blog/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

Rails_Blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # before_filter :current_user, only: [:create, :destroy]
  # before_filter :current_user,   only: :destroy

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(content: params[:content])
    if @post.save
    flash[:notice] = "Blog post created!"
    redirect_to current_user 
    end
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

Rails_Blog/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.where(email: params[:user][:email]).first
  	if @user && @user.password == params[:user][:password]
  		session[:user_id] = @user.id
  		flash[:notice] = "You're signed in!"
  		redirect_to @user

  	else
  		flash[:alert] = "Oops, something went wrong. Try logging in again."
  		redirect_to sessions_new_path
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to root_path
  end
end

Rails_Blog/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :current_user, only: [:index, :edit, :update]
  before_filter :current_user,   only: [:edit, :update]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
     @user = User.new(params[:user])
    if @user.save
      redirect_to @user 
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @current_user = current_user
    @post = @user.posts.new 
    @comment = @user.comments.new
  end

  def edit
     @user = current_user 
  end

  def update
    @user = current_user
      if @user.update_attributes(params[:user])
        flash[:notice] = "Profile updated"
        redirect_to @user 
      else 
        render 'edit'
      end
  end

  def destroy
     @user = current_user
      if @user.destroy
      flash[:notice] = "User destroyed." 
      redirect_to root_path
    end
  end

end

Rails_Blog/app/helpers/comments_helper.rb
module CommentsHelper
end

Rails_Blog/app/helpers/friendships_helper.rb
module FriendshipsHelper
end

Rails_Blog/app/helpers/posts_helper.rb
module PostsHelper
end

Rails_Blog/app/helpers/sessions_helper.rb
module SessionsHelper
end

Rails_Blog/app/helpers/users_helper.rb
module UsersHelper
end

Rails_Blog/app/views/friendships/create.html.erb
<h1>Friendships#create</h1>
<p>Find me in app/views/friendships/create.html.erb</p>

Rails_Blog/app/views/friendships/destroy.html.erb
<h1>Friendships#destroy</h1>
<p>Find me in app/views/friendships/destroy.html.erb</p>

Rails_Blog/app/views/home/index.html.erb
 <div class="container">
    <center><h1>Welcome to Bumbler!</h1><small>Where you come for your funny fix.</small></center><br>
     	<center><div id="log_in">
        	<small>Log in right here.</small>
       		<%= link_to 'Log In', sessions_new_path %>
        <br>
        	<small>Not a member yet, sign up here!</small>
        	<%= link_to 'Sign Up', new_user_path %>
        	
      </div></center> 
   </div>
</div>

Rails_Blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bumblr</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<style>
  body{
       background-color: gray;
       color:white;
  }
</style>
  <header class="default_header">
      <div >
        <h4> Bumblr!</h4>
        <%= link_to 'All Users', users_path %>
        <%= link_to 'Home', root_path %>
        <%= link_to 'Log In', sessions_new_path %>
        <%= link_to 'Log Out', sessions_destroy_path, method: :delete %>
        <%= link_to 'Sign Up', new_user_path %>
      </div>
  </header>
  <hr>

  <body>

  <div class="container-fluid">
    <div class="row-fluid">

  <hr>
    <%= flash[:notice] if flash[:notice] %>
    <%= flash[:alert] if flash[:alert] %>
    <hr>
    <%= yield %>
    </div>
  </div>
  </body>
  
   
  
</html>

Rails_Blog/app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

Rails_Blog/app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

Rails_Blog/app/views/posts/index.html.erb
<h1>Read on...</h1>

<% @posts.each do |post| %>
	<h2><%=%></h2>
	<p>
	<%= post.content %>
	by <%= post.user.first_name %>
	<%= post.user.last_name %>
	</p>
<% end %>

Rails_Blog/app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>

Rails_Blog/app/views/posts/show.html.erb
<h1><%= Blog on...%></h1>

<%= @post.content %>

<p>
<%= link_to "Back", posts_path %>

<%= link_to "Edit", edit_post_path(@post) %>

<%= link_to "Delete", @post, :method => :delete, :confirm => "Are you sure?" %>
</p>

<div id="homepage_content">
		<span class="homepage_subheader">Create a new post!</span>
			<div id="homepage_login">
				<%= form_for @post do |f| %>
			  		<%= f.label :content, 'Do tell...' %><br>
			  		<%= f.text_area :content %>
				  	<%= f.submit %>
				 <% end %>
	    	</div>
	</div>

	<div id="posts">
	    <h1 class="all_posts">
	       Your Posts
	    </h1>

		<% @user.posts.each do |post|%>
		    <hr color="grey">
			<div class="post_first_name">
			   by <%=post.user.first_name + " " + post.user.last_name %>
			</div> 
			<div class="post_content"> 
			   <%= post.content %>
			</div>
			<br>
			<p>
		<%= link_to "Back", posts_path %>
		
			</p>
		<% end %>	
	<div>

Rails_Blog/app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

Rails_Blog/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

Rails_Blog/app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

Rails_Blog/app/views/users/edit.html.erb
<h1>Sign Up</h1>


<%= form_for @user do |f| %>
	<%= f.label :first_name %>
	<%= f.text_field :first_name, autofocus: true %>
	<%= f.label :last_name %>
	<%= f.text_field :last_name %>
	<%= f.label :email %>
	<%= f.text_field :email%>
	<%= f.label :password %>
	<%= f.password_field :password %>
	<%= f.submit %>
<% end %>

Rails_Blog/app/views/users/index.html.erb
<h1>Check out other people on Bumblr!</h1>

<% @users.each do |user| %>
	<div>
		<%= user.first_name %>
		<%= user.last_name %>
		<%= link_to 'See More', user %>
	</div>
<% end %>

Rails_Blog/app/views/users/new.html.erb
<h1>New User? Sign up right here.</h1>


<%= form_for @user do |f| %>
	<%= f.label :first_name %>
	<%= f.text_field :first_name, autofocus: true %>
	<%= f.label :last_name %>
	<%= f.text_field :last_name %>
	<%= f.label :email %>
	<%= f.text_field :email%>
	<%= f.label :password %>
	<%= f.password_field :password %>
	<%= f.submit %>
<% end %>

Rails_Blog/app/views/users/show.html.erb
<!-- <h1>Users#show</h1> -->
<style>
  body{
  	   background-image: url("/images/plaid.geometric.jpg");
       color:white;
  }
</style>

<header>
	<h1 id="welcome_name">Welcome, <%=@user.first_name if @user %></h1>
		
</header>
<br>
<hr>

<div id="about_me">

	<div class="profile_stats">
		Name: <%= @user.first_name %> 
			  <%= @user.last_name %><br>
		Email: <%= @user.email %><br>
			<% if @user == @current_user %>
				<%= link_to 'Edit', edit_user_path(@user) %>   
				<%= link_to 'Delete', @user, method: :delete %>
			<% end %>
	</div>
</div>


	<div id="homepage_content">
		<span class="homepage_subheader">Create a new post.</span>
			<div id="homepage_login">
				<%= form_for(@post) do |f| %>
			  		<%= f.label :content, 'Do tell...' %><br>
			  		<%= f.text_area :content, size: "50x15" %>
				  	<%= f.submit %>
	    	</div>
	    	<% end %>
	</div>

	<div id="posts">
	    <h1 class="all_posts">Posts</h1>
		<% @user.posts.each do |post|%>
<hr>
		<div class="post_content"> 
			<%= @post.content %>
		</div>
<br>
		<p>
			<%= link_to "Back", posts_path %>
			<%= link_to "Edit", edit_post_path(@user)  %>
			<%= link_to "Delete", @post, method: :delete %>
		<% end %>	
		</p>
			<%= form_for(@comment) do |f| %>
			<%= f.text_area :content, size: "60x4" %><br>
			<%= f.submit %>
				<% end %>

Rails_Blog/app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>